export const productCategories = [
  "beauty",
  "fragrances",
  "furniture",
  "groceries",
  "home-decoration",
  "kitchen-accessories",
  "laptops",
  "mens-shirts",
  "mens-shoes",
  "mens-watches",
  "mobile-accessories",
  "motorcycle",
  "skin-care",
  "smartphones",
  "sports-accessories",
  "sunglasses",
  "tablets",
  "tops",
  "vehicle",
  "womens-bags",
  "womens-dresses",
  "womens-jewellery",
  "womens-shoes",
  "womens-watches",
] as const;

export enum ProductSortBy {
  TITLE_ASC = "title_asc",
  TITLE_DESC = "title_desc",
  BRAND_ASC = "brand_asc",
  BRAND_DESC = "brand_desc",
  NONE = "none",
}
